### ISSUE TITLE
`email_pysar_results` List Index Out of Range Error

### ISSUE THREAD

**Issue by Ovec8hkin** [geodesymiami/rsmas_insar#100]
`run_operations.py` exits prematurely due to errors thrown in `process_rsmas.py`, specifically the one listed below.

```
Traceback (most recent call last):
  File "/nethome/jaz101/test/test4/rsmas_insar/sources/rsmas_isce/process_rsmas.py", line 124, in <module>
    prs.run_pysar(inps, start_time)
  File "/nethome/jaz101/test/test4/rsmas_insar/sources/rsmas_isce/_processSteps.py", line 399, in run_pysar
    putils.email_pysar_results(time_str, inps.custom_template)
  File "/nethome/jaz101/test/test4/rsmas_insar/sources/rsmas_isce/_process_utilities.py", line 366, in email_pysar_results
    template_file = glob.glob('PYSAR/INPUTS/*.template')[0]
IndexError: list index out of range
```

This error needs to be solved before `run_operations.py` will work as expected. To test, checkout the `run_operations_new` branch from git, and run the below command:

`run_operations.py --sheet_id 1CPg29RhjBVdWLdTk50RyoX0Fk0Ab-piZMMwJRvHIipc`

**Comment by falkamelung** [comment]
I only saw this today.  You don't have any data in your PYSAR folder. Something is wrong with your versions/branches or RSMAS_isce or pysar. I am running testGalapagosSenDT128 in my area and it seems to work fine (but has not finished yet)
@Ovec8hkin @mirzaees 

/projects/scratch/insarlab/famelung/testGalapagosSenDT128

**Comment by Ovec8hkin** [comment]
@falkamelung You're running `run_operations.py` from the `run_operations_new` branch on your end, and it doesn't throw that error? That would imply my version of PySAR is outdated.

**Comment by falkamelung** [comment]
Yes. It was a too old PYSAR version. I updated your PySAR (your test4) and pysarApp.py works fine.  However, there is something else weird with your branch (I am on your master). When I run
` process_rsmas.py /nethome/jaz101/insarlab/OPERATIONS/TEMPLATES/testGalapagosSenDT128.template --startpysar —submit`
It runs fine but it does not submit as a job. Something is not updated. I did not try updating your rsmas_isce

Also, when you run the test data (see below) it does not submit as a job, but otherwise works fine.

`process_rsmas.py /nethome/jaz101/test/test4/rsmas_insar/samples/unittestGalapagosSenDT128.template --startmakerun —submit`
------------------------------------------------------
Falk Amelung
Professor
Department of Marine Geosciences
Rosenstiel School of Marine and Atmospheric Sciences
University of Miami
4600 Rickenbacker Causeway
Miami, FL 33149
USA
Tel: 305 421 4949
E-mail: famelung@rsmas.miami.edu<mailto:famelung@rsmas.miami.edu>
Web: http://insar.rsmas.miami.edu
InSAR data:
http://insarmaps.miami.edu




On Mar 19, 2019, at 7:57 PM, Joshua Zahner <notifications@github.com<mailto:notifications@github.com>> wrote:


@falkamelung<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffalkamelung&data=02%7C01%7Cfamelung%40rsmas.miami.edu%7C556015ed3e5d47a14bc208d6accefe2b%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C636886402358842095&sdata=PmqnDRyxpNPNDdWMND1mzSAgYJx%2F2HDyskHagFDvMh8%3D&reserved=0> You're running run_operations.py from the run_operations_new branch on your end, and it doesn't throw that error? That would imply my version of PySAR is outdated.

**Comment by falkamelung** [comment]
I would think if you just merge your new run_operations.py (and whatever is run_operations specific) into master things will work.
------------------------------------------------------
Falk Amelung
Professor
Department of Marine Geosciences
Rosenstiel School of Marine and Atmospheric Sciences
University of Miami
4600 Rickenbacker Causeway
Miami, FL 33149
USA
Tel: 305 421 4949
E-mail: famelung@rsmas.miami.edu<mailto:famelung@rsmas.miami.edu>
Web: http://insar.rsmas.miami.edu
InSAR data:
http://insarmaps.miami.edu




On Mar 19, 2019, at 9:52 PM, Amelung, Falk C <famelung@rsmas.miami.edu<mailto:famelung@rsmas.miami.edu>> wrote:

Yes. It was a too old PYSAR version. I updated your PySAR (your test4) and pysarApp.py works fine.  However, there is something else weird with your branch (I am on your master). When I run
` process_rsmas.py /nethome/jaz101/insarlab/OPERATIONS/TEMPLATES/testGalapagosSenDT128.template --startpysar —submit`
It runs fine but it does not submit as a job. Something is not updated. I did not try updating your rsmas_isce

Also, when you run the test data (see below) it does not submit as a job, but otherwise works fine.

`process_rsmas.py /nethome/jaz101/test/test4/rsmas_insar/samples/unittestGalapagosSenDT128.template --startmakerun —submit`
------------------------------------------------------
Falk Amelung
Professor
Department of Marine Geosciences
Rosenstiel School of Marine and Atmospheric Sciences
University of Miami
4600 Rickenbacker Causeway
Miami, FL 33149
USA
Tel: 305 421 4949
E-mail: famelung@rsmas.miami.edu<mailto:famelung@rsmas.miami.edu>
Web: http://insar.rsmas.miami.edu
InSAR data:
http://insarmaps.miami.edu<https://nam01.safelinks.protection.outlook.com/?url=http%3A%2F%2Finsarmaps.miami.edu&data=02%7C01%7Cfamelung%40rsmas.miami.edu%7Ce197e573a4aa4466917b08d6acdf27d3%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C636886471772429921&sdata=EsrGJkHpwOX3bZVadXWCxMFW4k2Kb2eNn5HwVVt%2FNQA%3D&reserved=0>




On Mar 19, 2019, at 7:57 PM, Joshua Zahner <notifications@github.com<mailto:notifications@github.com>> wrote:


@falkamelung<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffalkamelung&data=02%7C01%7Cfamelung%40rsmas.miami.edu%7Ce197e573a4aa4466917b08d6acdf27d3%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C636886471772439926&sdata=Wu5KQuqPWOABivPaM%2F04H9uYey9yhRpFqsz0A72Tz8M%3D&reserved=0> You're running run_operations.py from the run_operations_new branch on your end, and it doesn't throw that error? That would imply my version of PySAR is outdated.

**Comment by falkamelung** [comment]
My response resolves, this, right? I am closing the issue.
