### ISSUE TITLE
Move `overwrite_stored_date_file` to `process_rsmas.py`

### ISSUE THREAD

**Issue by Ovec8hkin** [geodesymiami/rsmas_insar#112]
We should move the `overwrite_stored_date_file` function that is used in `run_operations.py` to overwrite the the `stored_date.date` file to the end of `process_rsmas.py`. This will make sure that the `stored_date.date` file is not overwritten if `process_rsmas.py` fails in the middle of execution. This also make more sense, as the updating of the `stored_date.date` file is more of a `process_rsmas.py` routine than a `run_operations.py` routine.

This can be easily accomplished by adding a `--update` command-line parameter to `process_rsmas.py` and executing the `overwrite_stored_date_file` function if that parameter is given.

**Comment by falkamelung** [comment]
Can’t we do this within run_operations after process_rsmas process successfully conpleted? It would be preferred to keep run_opertions functionality out of process_rsmas. Process_rsmas may be used by others but probably not run_operations

Sent from my IPhone.

On Apr 6, 2019, at 9:24 AM, Joshua Zahner <notifications@github.com<mailto:notifications@github.com>> wrote:


We should move the overwrite_stored_date_file function that is used in run_operations.py to overwrite the the stored_date.date file to the end of process_rsmas.py. This will make sure that the stored_date.date file is not overwritten if process_rsmas.py fails in the middle of execution. This also make more sense, as the updating of the stored_date.date file is more of a process_rsmas.py routine than a run_operations.py routine.

This can be easily accomplished by adding a --update command-line parameter to process_rsmas.py and executing the overwrite_stored_date_file function if that parameter is given.

**Comment by Ovec8hkin** [comment]
Thats how its done at the moment. But it `process_rsmas` fails part of the way through, the `stored_date.date` file is going to be updated anyway and appears as though `process_rsmas` succeeded.

I don't really view this as `run_operations` functionality. It seems more like something `process_rsmas` should conditionally handle, since its reliant on `process_rsmas` finishing without errors

**Comment by falkamelung** [comment]
Yeah, so can’t we just check whether the process was successful before updating?  Currently the exit status may not be indicative of whether it was successful, but this can be fixed.
That is is unclear whether or not process_rsmas was successful is our main limitation right now and I would like to put efforts on improving this

If there is something I don’t understand we could have a clearly named —update_stored_date_for_run_operations option.

Sent from my IPhone.

On Apr 6, 2019, at 3:38 PM, Joshua Zahner <notifications@github.com<mailto:notifications@github.com>> wrote:


Thats how its done at the moment. But it process_rsmas fails part of the way through, the stored_date.date file is going to be updated anyway and appears as though process_rsmas succeeded.

I don't really view this as run_operations functionality. It seems more like something process_rsmas should conditionally handle, since its reliant on process_rsmas finishing without errors

**Comment by Ovec8hkin** [comment]
`—update_stored_date_for_run_operations` <-- this is what I suggested doing (but shorten the option name).

We can't just wait in `run_operations` to see if `process_rsmas` failed, because to do so will mean we can only run datasets in series rather than in parallel, as would be preferred. Thus, at the moment, `run_operations` submits a `process_rsmas` call as a job, then updates the `stored_date.date` file, assuming that `process_rsmas` isn't going to fail mid routine. We can't collect the the return status of the `process_rsmas` calls, because there could be multiple ones going on simultaneously. 

To mitigate the risk of updating the `stored_date.date` file erroneously, I want to move that routine to the end of `process_rsmas` as show below:

```python
...

if inps.update_stored_date:
     overwrite_stored_date_file()

```

This way, if `process_rsmas` fails mid routine, then the `stored_date.date` file is not updated, and `run_operations` will try it again the next day. Leaving it within the conditional, allows for you to still have manual control over `process_rsmas` and the ability to run `process_rsmas` without updating the `stored_date.date` file.
