### ISSUE TITLE
Cleaning up requirement.txt

### ISSUE THREAD

**Issue by mirzaees** [geodesymiami/rsmas_insar#124]
we have a requirements.txt file but it is not in a good way. it is a long list with all versions included which every few days when a package or conda is updated, some of them may disappear and conflicts raise.
We need a requirement.txt file that only contains main necessary packages without version specified. 
I don't know which packages are independent that should come on the list and which are not, any idea?

**Comment by falkamelung** [comment]
It would be really good to resolve this. And we need this for the new pysar parallel execution. Can't we just do a `pip install rsmas_insar`? We need a combination of the isce requirements, pysar requirements and our own requirements.   ISCE can now be installed using Conda.  Sara plans to commit a new version of our setup that uses `conda install isce`, correct Sara? Maybe we should address this once we have this.
https://github.com/isce-framework/isce2/blob/master/README.md
https://github.com/yunjunz/PySAR/blob/master/requirements.txt

@2gotgrossman  in the case you are not aware, we currently use install_miniconda3,csh for all this. Our current solution is to add  at the end of the script another `conda install module --yes` command but it does not always work, and is slow.

**Comment by Ovec8hkin** [comment]
Anything that comes installed with miniconda by default should be omitted from the `requirements.txt` file. Only those packages and modules that are not installed by default need to be listed there. An easy way to do this would be to lookup a list of those modules that come with miniconda and remove them from our `requirements.txt` file. That should shorten things up significantly.

**Comment by falkamelung** [comment]
Good idea, but it would remove the number of dependencies by ~30 (from 300). 

Following Josh's comment I put  a requirements.txt together based on the ISCE and PYSAR link above.  With this the miniconda installation works fine, but the ice compilation gives errors. This happens because our ISCE installation uses  `gcc` from conda whereas the ISCE GitHub version assumes that conda is installed.  So  we need to figure out what gcc dependencies we need to put into our requirements file.   This may not be relevant if the conda installation of isce works fine. So lets first get the setup adjusted  (@mirzaees  wanted to to this, right?) and go from there.
```
cython
gdal
git
h5py
libgdal
pytest
numpy
fftw
scipy
basemap
scons
opencv
basemap
cdsapi
cvxopt
dask[complete]>=1.0,<2.0
dask-jobqueue>=0.3,<1.0
eccodes
lxml
matplotlib
netcdf4
openmp
pygrib
pyhdf
pykdtree
pykml
pyproj
pyresample
scikit-image
natsort
```

**Comment by mirzaees** [comment]
I tried to install with 'conda install isce' and the requirements.txt list above.  
conda is supposed to find the dependancies and match versions,
so I added isce2 to the list and the isce channel to condarc but still gcc-5 cannot be installed and it fails!
I think it is better to stick to the release version instead of conda version of isce as it is more stable

**Comment by falkamelung** [comment]
I did a bare miniconda installation and `conda install isce2 -c piyushrpt` and it worked fine.  We just need to add a few more of the modules required for pysar, `conda install dask[complete] --yes` and dask job queue worked also. So this should be easy.

**Comment by mirzaees** [comment]
we need gcc-5 but I can't install it. here is the error I get:

failed
ERROR conda.core.link:_execute(568): An error occurred while installing package 'psi4::gcc-5-5.2.0-1'.
LinkError: post-link script failed for package psi4::gcc-5-5.2.0-1

**Comment by falkamelung** [comment]
The problem was the tippecanoe installation which is required for insarmaps. It compiles using gcc4.9 (now added as a module). On a computer without a recent gcc it would not compile.

It would be nice to get `conda install gcc` or `conda install libgcc` to work. @2gotgrossman, when you have some time, maybe you can give it a shot?

This version has all pysar dependencies installed. @yunjunz, we should be ready to switch to dask now.

The installation now does `conda install requirements_pysar.txt`. 

@yunjunz , when you get a chance, please clean  up the pysar requirements file. When I do `conda install $PYSAR_HOME/requirements.txt --yes` I get the errors below. The culprits are `pykml` and/or `pyaps` which may need to installed separately (look at the rsmas_insar README).

```
conda install $PYSAR_HOME/requirements.txt --yes
Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - /nethome/famelung/test/test1/rsmas_insar/sources/pysar/requirements.txt

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://conda.anaconda.org/omnia/linux-64
  - https://conda.anaconda.org/omnia/noarch
  - https://conda.anaconda.org/psi4/linux-64
  - https://conda.anaconda.org/psi4/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by yunjunz** [comment]
@falkamelung, please use https://github.com/insarlab/PySAR/blob/master/docs/conda.txt for `conda install`, it is cleaned. The requirements.txt is meant for pip install (but I did not test) and dependency graph in github.

**Comment by falkamelung** [comment]
resolved and/or superseded
