### ISSUE TITLE
How to add option to skip master topo processing?

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/rsmas_insar#208]
When a pegasus error occurs (which happens frequently) I want to quickly rerun wIthout the master processing, as this takes a long time, i.e. it should not write the following line into the `run_1_unpack*` file :
```
SentinelWrapper.py -c /projects/scratch/insarlab/famelung/UbinasSenDT127/configs/config_master
```
Any suggestion of the least intrusive way to do this? We could add an option to the run_file-generating-script  to not write this line, but it is unclear whether JPL would accept the PR. Or shall we add an option to `execute_runfiles.py` to optionally run a rsmas script before/after certain processing scripts?  It could be handy to have the second option for efficient debugging. How do you think?

**Comment by mirzaees** [comment]
This is not a good idea
- without the master being processed, you can not run other steps, and repeat creating runfiles after step 1 processed, will produce errors unless you delete the outputs from run_1_* like slaves.  so it is not a good idea to remove this line from `run_1_unpack*`. 
- `execute_runfiles.py` submits all commands in a run file as separate batch jobs and does not control which line is which. and it is not efficient to add such exception! because it does not occur all the time.
- best way is to manually modify run_1_* and keep a copy of that. debug can not be automatic in such cases, anyway you need to check it manually

**Comment by falkamelung** [comment]
It could be added to the code, but it would make it unclear. OK. Will manually edit.
