### ISSUE TITLE
Copy to tmp issue

### ISSUE THREAD

**Issue by mirzaees** [geodesymiami/rsmas_insar#498]
Hi @falkamelung 

- There is a command in copy_to_tmp.bash which is unknown to me, it shows error for me, is it an old temporary thing that should be deleted?

https://github.com/geodesymiami/rsmas_insar/blob/d2a628fa28fbf820b276c9ca4d945c50c7474a1f/minsar/utils/copy_to_tmp.bash#L50

- Also run_workflow.bash should be updated to find run_files_tmp instead of run_files

**Comment by falkamelung** [comment]
That has to be there. Shell scripts instead of code in the job files.

Will be there soon

Sent from my IPhone.

On Sep 23, 2021, at 12:26 PM, Sara Mirzaee ***@***.***> wrote:

﻿
CAUTION: This email originated from outside the organization. DO NOT CLICK ON LINKS or OPEN ATTACHMENTS unless you know and trust the sender.


Hi @falkamelung<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffalkamelung&data=04%7C01%7Cfamelung%40rsmas.miami.edu%7C7f1818c198cd4cb9916c08d97eaee325%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C637680111885990598%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=i49MjYZOlk5cDoAF31pwJJGvukA8%2BrdiK4F%2FIltvuls%3D&reserved=0>

  *   There is a command in copy_to_tmp.bash which is unknown to me, it shows error for me, is it an old temporary thing that should be deleted?

https://github.com/geodesymiami/rsmas_insar/blob/d2a628fa28fbf820b276c9ca4d945c50c7474a1f/minsar/utils/copy_to_tmp.bash#L50<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgeodesymiami%2Frsmas_insar%2Fblob%2Fd2a628fa28fbf820b276c9ca4d945c50c7474a1f%2Fminsar%2Futils%2Fcopy_to_tmp.bash%23L50&data=04%7C01%7Cfamelung%40rsmas.miami.edu%7C7f1818c198cd4cb9916c08d97eaee325%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C637680111886000556%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MIJEUk7IVlV2H5FNPqLQAws1nk%2FPg%2BrcLJCv3wIomPA%3D&reserved=0>

  *   Also run_workflow.bash should be updated to find run_files_tmp instead of run_files

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgeodesymiami%2Frsmas_insar%2Fissues%2F498&data=04%7C01%7Cfamelung%40rsmas.miami.edu%7C7f1818c198cd4cb9916c08d97eaee325%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C637680111886000556%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=VWiW%2BHdx8ZYSKiElaZF5MVrP0K5xx%2Bj1qWHD%2Fp5dcjo%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACVFHXD4ZJQAIRZWPUNA6X3UDNILBANCNFSM5EUCMFXA&data=04%7C01%7Cfamelung%40rsmas.miami.edu%7C7f1818c198cd4cb9916c08d97eaee325%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C637680111886010480%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=bte1phCsuq307iQCi9mItRbr9H5DzH4igdYNkCMbkgg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cfamelung%40rsmas.miami.edu%7C7f1818c198cd4cb9916c08d97eaee325%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C637680111886010480%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ScJ3ODtwC11iT6DTrTm%2Br7gA5%2BPBJel%2FfPoUzkxIhNM%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cfamelung%40rsmas.miami.edu%7C7f1818c198cd4cb9916c08d97eaee325%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C637680111886020466%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=i08SLexKDcKIj%2FROyBcqiUOJ0gdZqrdKtL1waSKpdjA%3D&reserved=0>.

**Comment by mirzaees** [comment]
Hi @Ovec8hkin 

Do you know what this 'dummy-to-pop' line in copy_to_tmp.bash is? 
I recently installed everything new and it throws an error

**Comment by Ovec8hkin** [comment]
This was something that @falkamelung had in the initial scripts that I converted. I left it there so as to not mess anything up. Feel free to remove it and test if anything fails.

**Comment by mirzaees** [comment]
@Ovec8hkin Thank you for confirming, I'll just remove it
